#if !defined(TCM_CONFIG_VERSION_HPP__)
#define TCM_CONFIG_VERSION_HPP__

#include "macro.hpp"

#define TCM_VERSION_MAJOR 0
#define TCM_VERSION_MINOR 1
#define TCM_VERSION_PATCH 0

#define TCM_VERSION TCM_STR(TCM_VERSION_MAJOR) "." TCM_STR(TCM_VERSION_MINOR) "." TCM_STR(TCM_VERSION_PATCH)

#endif // TCM_CONFIG_VERSION_HPP__
